name: 'branchMatchRegex'
description: 'Check if the current branch matches a regex pattern'
author: 'IamPekka058 <59747867+IamPekka058@users.noreply.github.com>'


inputs:
  regex:
    description: 'The regex pattern to match the branch name against'
    required: false
    default: ''
  path:
    description: 'The path to the file containing the regex pattern'
    required: false
    default: ''
  useDefaultPatterns:
    description: 'Use default patterns for branch matching'
    required: false
    default: false
  failOnUnmatchedRegex:
    description: 'Fail the action if the branch does not match the regex pattern'
    required: false
    default: true
  branchName:
    description: 'The branch name to check against the regex pattern'
    required: false
    default: ${{ github.head_ref }}
  useWildcard:
    description: 'Use wildcard matching instead of regex'
    required: false
    default: false
  
runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'check-circle'
  color: 'blue'