name: Test branchMatchRegex Action
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Test with list
        uses: IamPekka058/branchMatchRegex@main
        with:
          regex: |
            - 'feature/*'
            - 'test/*'

      - name: Test with list
        uses: IamPekka058/branchMatchRegex@main
        with:
          regex: "['feature/*', 'test/*']"

      - name: Test with file
        uses: IamPekka058/branchMatchRegex@main
        with:
          path: .github/workflows/branches.yml
