name: Test branchMatchRegex Action
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Run branchMatchRegex action
        uses: ./
        with:
          regex: 'feature/*'
      
      - name: Run branchMatchRegex action
        uses: ./
        with:
          path: ./.github/workflows/branches.yml
